//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationBuilderAPIv1UnitTests.V1.Serialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShowPersonResponse1_json {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowPersonResponse1_json() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NationBuilderAPIv1UnitTests.V1.Serialization.ShowPersonResponse1.json", typeof(ShowPersonResponse1_json).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  
        ///   &quot;person&quot;:{  
        ///      &quot;birthdate&quot;:null,
        ///      &quot;city_district&quot;:null,
        ///      &quot;civicrm_id&quot;:null,
        ///      &quot;county_district&quot;:null,
        ///      &quot;county_file_id&quot;:null,
        ///      &quot;created_at&quot;:&quot;2016-01-14T02:15:09+11:00&quot;,
        ///      &quot;datatrust_id&quot;:null,
        ///      &quot;do_not_call&quot;:false,
        ///      &quot;do_not_contact&quot;:false,
        ///      &quot;dw_id&quot;:null,
        ///      &quot;email&quot;:null,
        ///      &quot;email_opt_in&quot;:true,
        ///      &quot;employer&quot;:null,
        ///      &quot;external_id&quot;:null,
        ///      &quot;federal_district&quot;:null,
        ///      &quot;fire_district&quot;:null,
        ///      &quot;first_name&quot;:&quot;Steven&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
